name: CI

on:
  push:
    branches: [ v3.13.x ]
  pull_request:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  appimage:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/build-appimage.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build-ubuntu:
    uses: ./.github/workflows/build-ubuntu.yml
    secrets: inherit

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  release:
    needs: [build-macos, build-ubuntu, build-windows]
    uses: ./.github/workflows/release.yml
    secrets: inherit
